spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/spring_batch?characterEncoding=UTF-8&serverTimeZone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: '@hongj81ak'
  batch:
    initialize-schema: never